[package]
name = "virtmach-attiny85"
version = "0.1.0"
authors = ["Sascha Klick <rustdev@sklick.de>", "Eric Wood <eric@ericwood.org>"]
edition = "2018"

[features]
default = ["rt"]
rt = ["attiny85-hal/rt"]

[dependencies]
panic-halt = "0.2.0"
avr-device = "0.3.0"
embedded-hal = "0.2.4"

[dependencies.attiny85-hal]
git = "https://github.com/rahix/avr-hal"
rev = "a202778"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"
debug-assertions = false

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
debug-assertions = false