[package]
name = "virtmach-attiny85"
version = "0.1.0"
authors = ["Sascha Klick <rustdev@sklick.de>", "Eric Wood <eric@ericwood.org>"]
edition = "2018"
resolver = "2"

[features]
default = ["rt", "gpio", "time", "uart_tx"]
rt = ["attiny-hal/rt"]
simavr = []
proc = []
time = []
gpio = []
i2c = []
uart_rx = []
uart_tx = []
pwm = []

[dependencies]
panic-halt = "1.0.0"
avr-device = { version = "0.8.1", features = ["attiny85"] }
embedded-hal = "1.0"

[dependencies.attiny-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e0b0105b11a7c4209fb1704276a7921c3139d5cb"
features = ["attiny85"]

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"
debug-assertions = false

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
debug-assertions = false

[dependencies.virtmach]
path = "../.."
default-features = false
features = ["int_math_nopow", "int_math_nosqr"]
